getId()
getName()
getNameKana()
getPrefId()
getPostalCode()
getAddressPrefectures()
getAddressMunicipality()
getAddressOther()
getMail()
getPassword()

setId($id)
setName($name)
setNameKana($nameKana)
setPrefId($prefId)
setPostalCode($postalCode)
setAddressPrefectures($addressPrefectures)
setAddressMunicipality($addressMunicipality)
setAddressOther($addressOther)
setMail($mail)
setPassword($password)


getId()
getName()
getType()
getUserId()
getCircleId()
getParentId()

setId($id)
setName($name)
setType($type)
setUserId($userId)
setCircleId($circleId)
setParentId($parentId)

getId()
getName()
getType()
getUserId()
getCircleId()
getParentId()

setId($id)
setName($name)
setType($type)
setUserId($userId)
setCircleId($circleId)
setParentId($parentId)


setId($id)
setAlPpSize($alPpSize)
setAlBdDirection($alBdDirection)
setAlBdMethod($alBdMethod)
setAlPpDirection($alPpDirection)
setAlBkNum($alBkNum)
setAlPpNum($alPpNum)
setFrClorbw($frClorbw)
setFrPpType($frPpType)
setInClorbw($inClorbw)
setInPpType($inPpType)
setObjId($objId)

getId()
getAlPpSize()
getAlBdDirection()
getAlBdMethod()
getAlPpDirection()
getAlBkNum()
getAlPpNum()
getFrClorbw()
getFrPpType()
getInClorbw()
getInPpType()
getObjId()

setId($id)
setName($name)
setPrefId($prefId)
setPostalCode($postalCode)
setAddressPrefectures($addressPrefectures)
setAddressMunicipality($addressMunicipality)
setAddressOther($addressOther)
setDeliveryName($deliveryName)
setPhoneNumber($phoneNumber)

getId()
getName()
getPrefId()
getPostalCode()
getAddressPrefectures()
getAddressMunicipality()
getAddressOther()
getDeliveryName()
getPhoneNumber()

SELECT * FROM object WHERE circle_id = 1 AND parent_id = 0