getId()
getName()
getNameKana()
getPrefId()
getPostalCode()
getAddressPrefectures()
getAddressMunicipality()
getAddressOther()
getMail()
getPassword()

setId($id)
setName($name)
setNameKana($nameKana)
setPrefId($prefId)
setPostalCode($postalCode)
setAddressPrefectures($addressPrefectures)
setAddressMunicipality($addressMunicipality)
setAddressOther($addressOther)
setMail($mail)
setPassword($password)


getId()
getName()
getType()
getUserId()
getCircleId()
getParentId()

setId($id)
setName($name)
setType($type)
setUserId($userId)
setCircleId($circleId)
setParentId($parentId)

getId()
getName()
getType()
getUserId()
getCircleId()
getParentId()

setId($id)
setName($name)
setType($type)
setUserId($userId)
setCircleId($circleId)
setParentId($parentId)


SELECT * FROM object WHERE circle_id = 1 AND parent_id = 0